sudo: required
language: ruby
services:
- docker
before_install:
- docker build -t scan-over-tor .
script:
- docker run -v $(pwd)/aquatone:/root/aquatone scan-over-tor skarlso.com 80.98.188.248
deploy:
  provider: s3
  access_key_id:
    secure: jkRoP1kGHjt9t6Uay93vMA3GmAMWeiFWam8svqF6INI4kjLOQHg7xW4rqEj7pqnCfbekVhxEtkamqjC9jNVoxBe7hEuBtcXJO04/IBc+srJDiXT0Nd4TLN23aL2VKdSs6LDsHcVo9VbHXnDQydwz2elO/LE9qvKRmUGt9KEtsJxbv3ZKVz3AKN/I3DAnbS2jVQZyp24dFM+Y1ALN5UiK3xzulCIaqKXmJyo2zDGzzswNI3yGz/Z5TWETjT5sgJxXPiSuAPGv5LpMfw53Xj065UHYzq6HAcjsKjzc2qQC+I05pi88jxSWRholqiEyx8YQG2bTSqQVfERXF8aQq2xn6XSze5mkt58CJBxZu2sM9sLcRhfYFnH9ERdtd03OXASlgQm7nNDWmR0r83e2ha2wyvxSAWAMbC525I9vM8oCJ+SJXlfib+5kvRFMYXi3HCxbPRk5/klP3aSW9D61WSVXIYjrar7JTVEojfcYPu27P/9fAYgWB1EvqoL0+Ijlx881hh+ovVKw8XxNiRmI+1Q3ZHnB7YFO+dOZjmiqr8riDL3L8AI+myBWu76JuMV4Nof9pb+nsps570G1X8F3AVH8kgjlviaBTXIDN1hjw/uU5iEPF3hFByp9M96UaEdp3i9BV+Bec03TnQD7LFhEWg8g3bqacLQ6l3g3BlIBBOdk4vE=
  secret_access_key:
    secure: WNhzGWeWNH1vlGP2/MIQY+xvuoJQCyV3UL+N5bUqGqZyIcqJFZSnqxFyivI04xw2McnqhRRopBpbqMkXvGF6LeqvD8bugKdPpHeK+En6S87wSXs4uSmlFLAnkbbC4/DgpIhd58xH8FVgUOeEohKw5DAfjWbHTtiy2tD7XmucLKqjMpwJWkMhcFu8Qz/7H/bfx5L04Eq5Lll19Q78G8DJLViYWF6O+MgNh0pL+AifJo3hZG70D9kbMHnytujGH3ctShAChhaxCBNQn/2fp8YwUCX1AyEMEuPLgoIMph80GzEnZzbuXr/lB+5S2Y/A64ykwuYngwe57CiRSYZRDwLulaPm8jDwEcAr7HjVwBABXi266Sf4Sj0YtfiB+sxkdTr+4bwVSTWFMXNW16o5QTgyPhRchINlI4QUYhdOiGHAi+IIIkg/ec86bjQ0/Ztplc/v1sw/DtNYlTMeC48AGk3+bJ3iU5fCj1DUH1/CHirA86neWy6mVKYAQSJW60dJmUccIeRQYP81BcXqxoXNxOVQ/UOHCOXAJyjgn/WK388i/KAZJiQBKMqU4sPA6cXV+5Vj+fr7633+Q9QcnUn0LDLiDJc62bDyID3/USOD49A9wkQWReXhX7CEFQ/7aPt6HggE6kxghdY4joRI7PPg3bIJFBX8uQh/X6lEUUR71OPV3Eg=
  bucket: scan-over-tor
  local_dir: aquatone
  skip_cleanup: true
